{% set name = "TimeChart" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 6e450902334623021225aa40cf8f534c498a58f676db817ae67d5629b79f5166

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - timechart = timechart_launcher.main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pydm >=1.6.0
    - pyqtgraph
    - qtpy
    - six

test:
  imports:
    - timechart
  requires:
    - pytest
    - pytest-qt
  commands:
    - timechart --help

about:
  home: https://github.com/slaclab/timechart
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Charting Tool based on PyDM
  description: |
    TimeChart is a Python Qt-based graphing application for control systems.
    It is intended to be the modern, feature-by-feature matching alternative
    to the Motif EPICS Strip Tool application.
  dev_url: https://github.com/slaclab/timechart
  doc_url: https://slaclab.github.io/timechart/

extra:
  recipe-maintainers:
    - jbellister-slac
    - YektaY
    - zllentz
    - klauer
